don't show ugly error messages if the pid file is not present or empty
git-svn-id: https://xpra.org/svn/Xpra/trunk@14050 3bb7dfac-3a0b-4e04-842a-767bc560f471

diff --git a/src/service/xpra b/src/service/xpra
--- a/src/service/xpra
+++ b/src/service/xpra
@@ -34,10 +34,14 @@ start() {
 }
 
 stop() {
-  PID=`cat $PIDFILE`
-  echo "Stopping service with pid $PID…" >&2
-  kill $PID
-  echo 'Service stopped' >&2
+  PID=`cat $PIDFILE 2> /dev/null`
+  if [ -z "$PID" ]; then
+	echo "Service not started, pidfile not found"
+  else
+	echo "Stopping service with pid $PID…" >&2
+  	kill $PID
+  	echo 'Service stopped' >&2
+  fi
 }
 
 case "$1" in
