build more codecs
using our private libraries if we find the pkgconfig files

diff --git a/tests/unittests/run b/tests/unittests/run
--- a/tests/unittests/run
+++ b/tests/unittests/run
@@ -15,9 +15,13 @@ SRC_DIR=`dirname $TESTS_DIR`
 
 PYTHON_VERSION=`$PYTHON --version | awk '{print $2}' | awk -F. '{print $1"."$2}'`
 
+if [ -d "/usr/lib64/xpra/pkgconfig" ]; then
+	EXTRA_ARGS=--pkg-config-path=/usr/lib64/xpra/pkgconfig
+fi
+
 INSTALL_ROOT="$SRC_DIR/dist/python${PYTHON_VERSION}"
 pushd $SRC_DIR
-$PYTHON ./setup.py install --without-printing  --without-docs --with-scripts --with-cython_tracing --home=$INSTALL_ROOT || die "failed to build"
+$PYTHON ./setup.py install --without-printing  --without-docs --with-scripts --with-cython_tracing --home=$INSTALL_ROOT $EXTRA_ARGS || die "failed to build"
 popd
 
 if [ `uname` == "Linux" ]; then
