workaround more setuptools breakage
--install-dir is documented but doesn't work - does not exist?
--prefix is preferred to --home apparently?
it replaces our script with some broken version that tries to locate the package when we already know where it lives - where is the option to not mess things up?

diff --git a/tests/unittests/run b/tests/unittests/run
--- a/tests/unittests/run
+++ b/tests/unittests/run
@@ -26,18 +26,20 @@ if [ -d "/usr/lib64/xpra/pkgconfig" ]; then
 	EXTRA_ARGS=--pkg-config-path=/usr/lib64/xpra/pkgconfig
 fi
 
-INSTALL_ROOT="$SRC_DIR/dist/python${PYTHON_VERSION}"
+INSTALL_PREFIX="$SRC_DIR/dist"
 pushd $SRC_DIR
-$PYTHON ./setup.py install --without-printing  --without-docs --with-scripts --with-cython_tracing --home=$INSTALL_ROOT $EXTRA_ARGS || die "failed to build"
+$PYTHON ./setup.py install --without-printing  --without-docs --with-scripts --with-cython_tracing --prefix=$INSTALL_PREFIX $EXTRA_ARGS || die "failed to build"
 popd
 
 if [ `uname` == "Linux" ]; then
 	export "GDK_BACKEND=x11"
 fi
-export PYTHONPATH=`ls -d $INSTALL_ROOT/lib*/python`:.
+export PYTHONPATH=`ls -d $INSTALL_PREFIX/lib*/python$PYTHON_VERSION/site-packages/xpra*`:.
 export PATH=$INSTALL_ROOT/bin:$PATH
-export XPRA_COMMAND=$INSTALL_ROOT/bin/xpra
-export XPRA_CONF_DIR=$INSTALL_ROOT/etc/xpra/
+export XPRA_COMMAND=$INSTALL_PREFIX/bin/xpra
+#undo the setuptools auto-damage:
+cp $SRC_DIR/fs/bin/xpra $XPRA_COMMAND
+export XPRA_CONF_DIR=$INSTALL_PREFIX/etc/xpra/
 
 pushd $UNITTESTS_DIR
 if [ "${XPRA_TEST_COVERAGE}" == "1" ]; then
