use both prefix and root to install datadirs
also set XPRA_APP_DIR so the unit tests can find the app data

diff --git a/tests/unittests/run b/tests/unittests/run
--- a/tests/unittests/run
+++ b/tests/unittests/run
@@ -12,7 +12,7 @@ export XPRA_TEST_DEBUG=${XPRA_TEST_DEBUG:-0}
 export XPRA_HIDE_SUBPROCESS_OUTPUT=${XPRA_HIDE_SUBPROCESS_OUTPUT:-1}
 export XPRA_TEST_COVERAGE=${XPRA_TEST_COVERAGE:-1}
 export PYTHON=${PYTHON:-python3}
-#Ubuntu will spew at too many warnings without this:
+#Ubuntu will spew far too many warnings without this:
 export NO_AT_BRIDGE=1
 #SAVED_PYTHONPATH=$PYTHONPATH
 
@@ -24,7 +24,7 @@ PYTHON_VERSION=`$PYTHON --version | awk '{print $2}' | awk -F. '{print $1"."$2}'
 
 INSTALL_ROOT="$SRC_DIR/dist/python${PYTHON_VERSION}"
 pushd $SRC_DIR
-$PYTHON ./setup.py install --without-printing --without-docs --with-scripts --with-cython_tracing --prefix=$INSTALL_ROOT $EXTRA_ARGS || die "failed to build"
+$PYTHON ./setup.py install --without-printing --without-docs --with-scripts --with-cython_tracing --prefix=$INSTALL_ROOT --root=$INSTALL_ROOT $EXTRA_ARGS || die "failed to build"
 popd
 
 if [ `uname` == "Linux" ]; then
@@ -37,6 +37,8 @@ echo "PYTHONPATH=${PYTHONPATH}"
 export PATH=$INSTALL_ROOT/bin:$PATH
 export XPRA_COMMAND=${XPRA_COMMAND:-$INSTALL_ROOT/bin/xpra}
 export XPRA_CONF_DIR=${XPRA_CONF_DIR:-$INSTALL_ROOT/etc/xpra/}
+export XPRA_APP_DIR=${XPRA_APP_DIR:-$INSTALL_ROOT/usr/share/xpra/}
+
 
 pushd $UNITTESTS_DIR
 if [ "${XPRA_TEST_COVERAGE}" == "1" ]; then
