fix path detection failure and don't spin forever
git-svn-id: https://xpra.org/svn/Xpra/trunk@23437 3bb7dfac-3a0b-4e04-842a-767bc560f471

diff --git a/osx/Helpers/PythonExecWrapper b/osx/Helpers/PythonExecWrapper
--- a/osx/Helpers/PythonExecWrapper
+++ b/osx/Helpers/PythonExecWrapper
@@ -20,6 +20,10 @@ full_path=$(cd "$(dirname "$0")"; pwd)
 tmp="$full_path"
 while [ "`basename "$tmp"`" != "Contents" ]; do
 	tmp=`dirname "$tmp"`
+	if [ "$tmp" == "/" ]; then
+		echo "cannot find /Contents/ in \"$full_path\""
+		exit 1
+	fi
 	if [ -z "$tmp" ]; then
 		echo "cannot find /Contents/ in \"$full_path\""
 		exit 1
