#1340: lmake it possible to run the wrapper from any subdirectory of "/Contents": we recurse up until we find it
git-svn-id: https://xpra.org/svn/Xpra/trunk@14176 3bb7dfac-3a0b-4e04-842a-767bc560f471

diff --git a/osx/Helpers/PythonExecWrapper b/osx/Helpers/PythonExecWrapper
--- a/osx/Helpers/PythonExecWrapper
+++ b/osx/Helpers/PythonExecWrapper
@@ -17,9 +17,15 @@ shift
 
 full_path=$(cd "$(dirname "$0")"; pwd)
 
-tmp=`dirname "$full_path"`
-bundle=`dirname "$tmp"`
-bundle_contents="$bundle"/Contents
+tmp="$full_path"
+while [ "`basename $tmp`" != "Contents" ]; do
+	tmp=`dirname "$tmp"`
+	if [ -z "$tmp" ]; then
+		echo "cannot find /Contents/ in \"$full_path\""
+		exit 1
+	fi
+done
+bundle_contents="$tmp"
 bundle_res="$bundle_contents"/Resources
 bundle_lib="$bundle_res"/lib
 bundle_bin="$bundle_res"/bin
